  Vue3/Estate[m
  Vue3/Estate_eventHandler[m
  Vue3/Estate_if&modal[m
* [32mVue3_blog/bootstrap[m
  Vue3_blog/start[m
  Vue3_estate/component1[m
  Vue3_estate/cssAnimation[m
  Vue3_estate/custom_event[m
  Vue3_estate/data-import&data-export[m
  Vue3_estate/modal_complete[m
  Vue3_estate/sorting[m
  Vue3_estate/v_model[m
  Vue3_estate/vif&modal[m
  Vue3_estate/vue_lifecycle[m
  Vue3_estate/watch[m
  Vue3_estate/watcher[m
  main[m
  [31mremotes/origin/HEAD[m -> origin/main
  [31mremotes/origin/Vue3/Estate_eventHandler[m
  [31mremotes/origin/Vue3_blog/start[m
  [31mremotes/origin/Vue3_estate/component1[m
  [31mremotes/origin/Vue3_estate/cssAnimation[m
  [31mremotes/origin/Vue3_estate/custom_event[m
  [31mremotes/origin/Vue3_estate/data-import&data-export[m
  [31mremotes/origin/Vue3_estate/modal_complete[m
  [31mremotes/origin/Vue3_estate/sorting[m
  [31mremotes/origin/Vue3_estate/v_model[m
  [31mremotes/origin/Vue3_estate/vif&modal[m
  [31mremotes/origin/Vue3_estate/vue_lifecycle[m
  [31mremotes/origin/Vue3_estate/watch[m
  [31mremotes/origin/main[m
